name: keeptrack
description: A Cross-platform Network Configuration and Auditing Tool for Small/Medium Server Spaces.

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  http: ^0.13.5
  flutter_secure_storage: ^6.0.0
  flutter_launcher_icons: ^0.10.0
  tuple: ^2.0.1
  mobile_scanner: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo_launch.png"
  min_sdk_android: 21 # android min sdk min:16, default 21